// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment.sql

package db

import (
	"context"
)

const listEnvironments = `-- name: ListEnvironments :many
SELECT name FROM environment WHERE deleted_at IS NULL
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
