// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetFlags(ctx context.Context) ([]GetFlagsRow, error)
	GetFlagsByEnvironmentName(ctx context.Context, name string) ([]GetFlagsByEnvironmentNameRow, error)
}

var _ Querier = (*Queries)(nil)
