// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddFlag(ctx context.Context, arg AddFlagParams) (FeatureFlag, error)
	GetFlags(ctx context.Context) ([]GetFlagsRow, error)
	GetFlagsByEnvironmentName(ctx context.Context, environmentName string) ([]GetFlagsByEnvironmentNameRow, error)
	ListEnvironments(ctx context.Context) ([]string, error)
	PageFlags(ctx context.Context, arg PageFlagsParams) ([]PageFlagsRow, error)
	SetEnvFlagToDefault(ctx context.Context, arg SetEnvFlagToDefaultParams) error
}

var _ Querier = (*Queries)(nil)
